#+title: Podstway Elektroniki 01, instrukcje do lab są bardzo bezużyteczne bo zkaładają że coś wiem.

* Półprzewodniki :: [[https://pl.wikipedia.org/wiki/P%C3%B3%C5%82przewodniki]]
** Samoistne
Są kijowe bo mają mało ładunków swobodnych(duża rezystywność).
Dlatego ich się nie stosuje.
** Domieszkowe (niesamoistne)
Domieszkowanie polega na wprowadzeniu i aktywowaniu atomoów domieszk do struktury kryształu. Domieszki są atomami pierwiastków niewychodzących w skład połprzeodnika samiostnego.
*** Półprzewodniki typu n
- Powstają przez wyprowadzenie domieszki mającej nadmiar elketronów(w stosunku do połprzewodnika samoistnego). Domieszkę nazywa się *donorową* (/"oddaje elektron"/).
- W takim półprzewodniku powstaje dodatkowy poziom energetyczny (*poziom donorowy*) w obszarze pasma wzbroninoego tuż pod poziomem przewodnictwa lub w nim.
- Nadmiar elektronów jest uwalniany do pasma przewodzenia prądu w postaci elektronów swobodnych zdolnych do przewdzenia prądu. *Przewodnictwo elektrnowe lub przewodnictwo typu n (z ang.negative, ujemny)*
*** Półprzewodniki typu p
- Powstają przez wyprowadzenie domieszki dającej niedobór elektronów (w stosunku do półprzewdonika samiostnego). Domieszkę nazywa się *akceptorową* (/przyjmuje elektron/)
- W takim półprzewodniku powstaje dodatkowy poziom energetyczny (*poziom akceptorowy*) w obszarze pasma wzbroninoego niewiele nad poziomem walencyjnym lub na nim.
* A potem znalazłem to i nie potrzebnie się męczyłem
[[https://www.youtube.com/watch?v=NA7M-h0pxns&list=PLpM1FRFG_H-gvpcqDR9XeAEJ9a8eCTdxo]]
