#+title: Wyklad 02
* Miejsce prawa autorekiego w systemie prawa
- Pierwotne :: dział prawa cywilnego, dziś -- część prawa własności intelektualnej.
- Prawo autorskie w znaczeniu przedmiotwym :: oznacza zespół norm prawnych regulujących stosunki związane z tworzenie, ekspolatacją i ochroną utworów, tzw. prawami pokrewnymi i niektórymi dobrami osobistymi.
- Prawo autorksie w znaczeniu przedmiotowym :: to zespół ozobistych i majątkowych uprawnień związanych z utworem.
* Żródła prawa autorkiego
- Ustawa z 4 lutego 1994 r. o prawie autorskim i prawach pokrewnych :: (tj. Dz. U. z 2021 r., poz 1062 ze zm.),dalej: pr. aut.
- Ustawa z 23 kwietnia 1964r -- Kodeks cywilny :: (t.j. Dz. U. z 2019r r. poz. 1145 ze zm.)
- prawo międzynarodowe :: (najważnejsze umowy multilateralne, konwencja berańska, konwencja powszechna, Traktat WIPO o prawie autorskim)
- Porawo Unit Europejeskiej :: (dyrektywy)
* Przedmot prawa autorskiego -- utwór
(synetyczna definicja utworu z art. 1 ust. 1 pr. aut.)
- Dobro niematerilane powinno być rezultatem pracy człowkeka (twórcy),
- stanowić przejaw działalności twórczej,
- mieć indywidualny charakter,
- zostać ustalony w jakiejkolwiek postaci
** Przesłanka "przejawu działalności twórczej" -- orginalności
- Utwór jest rezultatem działalności o charakterze kreacyjnym ( a nie wynikiem pracy rutynowej, szablonowej, zdeterminowanej przez przeznaczenie, materiał, wiążące schameaty pozbawiające twórcę swobody dokonywania wyboru),
- subiektywnie nowym wytworem intelektu, jest orginalany, przesłanka ujawniania
** Przesłanka indywidualności
- utwór jest wynikiem niepowtarzalnej osobowości twórcy ma charakter statsystycznie jednorazowy (niepowtarzalny); koncepcja statystycznej jednorazowości polekga na zbadaniu czy takiedzieło powstało już wcześcniej i czy jest staysycznie prawdopodbne wytworzenie go w przyszłości przez inną osobę
- Nie wyklucza to wystąpienia w wyjątkowych sytuacjach *twórczości paralelnej*
** Przesłanka ustalenia utworu
- Jest to jego uzwenętrzenie, które umożliwia percepcję utworu przez osoby trzecie inne niż twórca, dokonane w jakiejkolwiek postaci, nawet jeżeli utwór ma postać pracy magisterskiej, doktorskiej itp.;
- Ochrona autorskoprawna powstaje od chwili ustalenia utworu, jest niezależna od spełnienia jakichkolwiek formlaności, np. umieczeina zastrzeżeń na egzemplarzach utworu (art. 1 ust. 3i 4 pr. aut.)
* Co tak naprawdę jest chronione?
- Art. 1 ust. 2' :: zdanie pierwsze: Ochroną może być objęty wyłącznie sposób wyrażenia treści
- Forma -- :: z regóły bardziej oczywista ochrona
- Treść -- :: po spełnieniu przesłanek ochrony twórczosci;
- Dzieła podlegają ochronie w takim zakresie, w jakim są twórcze co może wyrażać się w treści i formie utworu lub tylko w formie utrowu, treści pozatekstowej
* Przykłądowy katalog utworów
*Art. 1ust. 2 pr. aut.*

Utwory:
1. Wytażone słowem, symbolami matematycznymi, znakami graficznymi(literackie,publicystyczne,naukowe,kartograficzne,porgramy komputerowe),
2. plastycznem
3. fotograficzne,
4. lutnicze,
5. wzornictwa przemysłowego
6. archtektoniczne, archtektoniczne-urbanistyczne i urbanistyczne,
7. muzyczne i słowno--muzyczne
8. sceniczne, sceniczno--muzyczne, chorograficzne i pantonomiczne,
9. audiowizualne (w tym filmowe)
* Rodzaje utworów
- art. 2 pr. aut -- :: utwór zależny i inspirowany
- art. 9 pr. aut -- :: utwór współautorski
- art. 10 pr. aut -- :: utwór połączony
- art. 11 pr. aut. -- :: utwór zbiorowy
- art. 12 pr. aut. -- :: utwór pracowniczy
- art. 14 pr. aut. -- ::  pracowniczy utwór naukowy
- art. 15a pr. aut. -- :: praca dyplomowa
* Utwory zależne i utwory inspirowane
- Utwór zależny -- :: o którym mówimy, wtedy, gdy osoba recypująca fragmęty cudzego utworu dokonałą daleko idących przekształceń, które połączone z jej wkłądem twórczym stanowią *nową jakość*, innaczej /"twórcza przeóbka"/ np. tłumaczenie, streszczenie, adptacja.
- Utwór inspirowany -- :: _który powstaje w wyniku pobudki(podniety) dostarczonej przez inny utwór_, przy czym nie chodzi o inspirację duchową, ale o powiązanie między dwoma utworami tj. utworem inspirującym i inspirowanym np. karykatura, parodia.
- Utwór zależny -- :: na egzemplarzach opracowania należy wmienić tytuł i twórcę utworu orginalnego; wykonanie autorskich praw majątkowych do utworu zależnego wymaga zgody twórcy utworu orginalnego.
