#+title: Wyklad 03
#+author: \textcopyleft
#+begin_comment
seksmisja ciemność widzę
reklama RFFM sprawdzić fakty każdy może - Jeży Szthur -- reklama z 2003r.
#+end_comment

* Źródła prawa
- ustawa z dn 4.02.1984 r. o prawie autorkim i prawach pokrewnych(tj. Dz.U z 2021 r poz. 1062 ze zm.) w skrócie pr.aut.
- regulamin zarządzania prawami autorskimi i prawami pokrewnymi oraz prawami własności przemysłowej praz zasad ich komercjalizacji z dn. 25.03.2015r. (załącznik do uchwały Senatu Politechniki Świętokrzyskiej nr 183/15)
* Juliusz Machulski vs RMF FM
- Spór o wykorzystanie w reklamie RM FM, z udziałem J. Stuhra, słów z filmu "Seksmisja"
- W filmie z 1983 r. "Ciemność, widzę ciemność, ciemność widzę"
- W reklamie telewizyjniej z 2003 r. :"Ciemność widzę, oj widzę ciemność"
- "Efekt twórczości (np. scenariusz czy wyreżyserowana wypowiedź aktora) _*zredukowany do krótkiej figury retorycznej* jest na tyle ogólny, że posiada wartość idei._" Jako taki o walorze abstrakcyjnym i ogólnym nies tnowi przemiotu prawa uatorksiego, gdyż traci cechę orginalności" -- wyrok SA w Krkowie z dn 5.03.2004r. I Aca 35/04
* Magdalena Czapińska vs PKP Intercity
- Sþór o wykorzystanie w reklamie PKP Intercity parafrazy framentu pisoenki "Remedium", autorstwa M. Czapińskiej, wykonanej przez Marylę Rodowicz
- W pisocence z 1978r. "Wsiąść do pociągu byle jakiego"
- W reklamie z 2009r. "Wsiądż do pociągu ... byle naszego"
- Sąd podkreślił, że pojedyńcze wtrazy nie są chronione prawem autroskim, ale _*ich wybór i scalenie wymaga orginalności i twórczego wysiłku*, co oznacza że posłużenie się fragmętem stanowi naruszenie prawa._ PKP wykorzystało w sej kampanii napopulraniejszy fragment szlageiru, jago wykorzystanie miało na celu wywołanie u odbirców pozytywnich skojarzenń i wspmnień. Sens słow piosenki został wypaczony, bo nie chodzi już o byle jaki pociąg, ale o pociąg konkretnego przewoźnika -- wyrok SA w Warszawie z listopada 2020 r.
* Podmiot prawa autorskiego
- Prawa autorkie przyługją twórcy :: o ile ustawa nie stanowi innaczej (art 8 ust. 1 pr. aut.)
- _autorskie prawa osobiste + aut. pr. majątkowe_ :: przysługują twórcy bądź współtwórcom(są to prawa nabyte pierwotne -- art 9 ust. 1 pr. aut.)
Twórcą jest osoba fizyczna, która stowrzyła utwór i której nazwosko lub pseudomin uwidoczniono na egzemplarzach utworu lub której autorstwo podano do publicznej widomości w jakikolwiek inny sposób związku z rozpowszechnieniem utworu.
* Wyjątki od zasady, że aut. prawa majątkowe przysługują twórcy dotyczą:
- Utworów zbiorowych :: producent lub wydawca (art. 11 pr. aut)
- Utworów audiowizualnych :: producentowi (art 70 ust. 1 pr. aut)
- Progrmów komputerowych :: stworzonych jako wynik wykonywania obowiązków ze stosunku pracy pracodawca, o ile umowa nie stanowi innaczej (art. 74 ust. 3 pr. aut.)
- Utworów pracowniczych :: w ogólności -- pracodawca, o ile ustawa lub umowa nie stanowią innaczej (art. 12 i 13 pr. aut.)
* Pracownicze utowry naukowe
- W przypadku utworów naukowych (art 14. pr. aut.) autorskie prawa majątkowe twórcóœ podlegają ograniczeniom ze względu na uprawnienia _instytucji naukowej, której przysługuje_:
  + pierwsześństwo publikacji
  + korzystania z materiału zawartego w utworze
  + udostępniania go osobom trzecim, jeżeli wynika, to z uzgodninego przeznaczenia utworu lub umowy
* Szczególne regulacje w odniesieniu do prac dyplomowych studentów/prac doktorackich doktoroatów -- art/ 15a pr. aut.
_Uczelnia na podstawie licencji ustnowionej ma:_
- pierwzeństwo opublokowania pracy dyplomowej studenta w ciągu 6 misięcy od obrony
- prawo korzystać bez wynagodzenia i bez konieczności uzyskania zgody autora z pracy
- prawo udostępniać pracę ministrowi właściewemu do spraw szkolnictwa wyższego i nauki
- prawo korzystać z ustwrów znajdujących się w prowadzonych przez ministra bazach danych, w celu sprwdzenia z wykorzystaniem Jednolitego Systemu Antyplagiatowego.
* Autorksie praw osobiste chronią więź twórcy z jego utworem, a w szczególności prawo do (art. 16. pr. aut.)
- Autorstwa utworu
- Oznaczenia utworu swoim nazwiskiem lub pseudonimem albo udostępninia go aniniomowo
- Ninaruszalności treści i formy utowru i jego rzetelnego wykorzystania
- Decydowania o pierwszym udostępniniu utworu publoczności
- Nadzoru nad sposobem korzystania z utworu
